name: Deploy Python App to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify the Python version you're using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install the dependencies from requirements.txt

      - name: Run the Python script (if applicable)
        run: |
          python your_script.py  # Replace with the actual script you want to run, if any

      - name: Build the application (if needed)
        run: |
          # Add any build steps if needed (e.g., generating assets, compiling files)
          echo "Build step (if any) goes here"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_access_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages  # The target branch for GitHub Pages
          folder: build  # The folder where your built assets are located (adjust if needed)
